on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        types: [string]
      buildArtifactName:
        required: true
        types: [string]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.buildArtifactName }}
          path: build
      - name: Publish Package
        run: |
          echo "pwd:"
          pwd
          echo "ls -la:"
          ls -la
          echo "ls -la build:"
          ls -la build
