on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        types: [string]
      skipTests:
        required: false
        types: [boolean]
        default: true
      buildArtifactName:
        required: false
        types: [string]
        default: 'build-artifact'
      

jobs:
  build:
    uses: ../../pipelines/dotnet/generic/build/build.yml
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}
  
  test:
    if: ${{ !inputs.skipTests }}
    needs: build
    uses: ../../pipelines/dotnet/generic/test/test.yml
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}

  publish-package:
    needs: ${{ inputs.skipTests && 'build' || 'test' }}
    uses: ../../pipelines/dotnet/generic/publish/publishPackage.yml
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}
