name: dotnet-libraries-entrypoint

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      skipTests:
        required: false
        type: boolean
        default: true
      buildDirectory:
        type: string
        default: 'build'
      buildArtifactName:
        type: string
        default: 'build-artifact'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build ${{ inputs.solutionPath }} -c Release -o ${{ inputs.buildDirectory }}
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.buildArtifactName }}
          path: ${{ inputs.buildDirectory }}
  
  publish-package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.buildArtifactName }}
          path: build
      - name: Publish Package
        run: |
          echo "pwd:"
          pwd
          echo "ls -la:"
          ls -la
          echo "ls -la build:"
          ls -la build
