name: dotnet-libraries-entrypoint

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      skipTests:
        required: false
        type: boolean
        default: true
      buildArtifactName:
        required: false
        type: string
        default: 'build-artifact'

jobs:
  run:
    uses: Kevin-Dohmen-Projects/pipelines-generic/templates/dotnet/libraries.yml@main
    with:
      solutionPath: ${{ inputs.solutionPath }}
      skipTests: ${{ inputs.skipTests }}
      buildArtifactName: ${{ inputs.buildArtifactName }}
