name: dotnet-libraries-entrypoint

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      skipTests:
        required: false
        type: boolean
        default: true
      buildArtifactName:
        required: false
        type: string
        default: 'build-artifact'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "does it work???"
  # run:
  #   uses: ./templates/dotnet/libraries.yml
  #   with:
  #     solutionPath: ${{ inputs.solutionPath }}
  #     skipTests: ${{ inputs.skipTests }}
  #     buildArtifactName: ${{ inputs.buildArtifactName }}
