on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      skipTests:
        required: false
        type: boolean
        default: true
      buildArtifactName:
        required: false
        type: string
        default: 'build-artifact'
      

jobs:
  build:
    uses: Kevin-Dohmen/pipelines-generic/.github/workflows/build.yml@main
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}
  
  test:
    if: ${{ !inputs.skipTests }}
    needs: build
    uses: Kevin-Dohmen/pipelines-generic/.github/workflows/test.yml@main
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}

  publish-package:
    needs: build
    uses: Kevin-Dohmen/pipelines-generic/.github/workflows/publishPackage.yml@main
    with:
      solutionPath: ${{ inputs.solutionPath }}
      buildArtifactName: ${{ inputs.buildArtifactName }}
